'use client';

import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
import {initialEntries,type Entry,kinds} from './content';
import './notebook.css';

type Chapter='about'|'work'|'lab'|'notes'|'shelf'|'studio'|'now'|'social';
const chapters: {id:Chapter;label:string;number:string;hint:string;x:number;y:number;rotation:number}[]=[
  {id:'work',label:'Things I’ve built',number:'01',hint:'Follow the system',x:19,y:28,rotation:-5},
  {id:'lab',label:'The experiment log',number:'02',hint:'Ask a better question',x:74,y:24,rotation:4},
  {id:'notes',label:'Notes to self',number:'03',hint:'Thinking, out loud',x:82,y:55,rotation:-3},
  {id:'shelf',label:'The rabbit holes',number:'04',hint:'An unfinished reading list',x:20,y:73,rotation:3},
  {id:'studio',label:'After the code',number:'05',hint:'Words. Frames. Frequencies.',x:57,y:80,rotation:-4},
  {id:'now',label:'Right now',number:'06',hint:'An open chapter',x:44,y:12,rotation:2},
];
const sequence:Chapter[]=['about','work','lab','studio','notes','shelf','now','social'];
const captions:Record<Chapter,string>={about:'THE PERSON / NOT THE JOB TITLE',work:'BUILD LOG / SYSTEMS WITH A PURPOSE',lab:'THE LAB / QUESTIONS BEFORE ANSWERS',notes:'MARGIN NOTES / THINKING OUT LOUD',shelf:'THE RABBIT HOLES / IDEAS THAT STAY',studio:'AFTER THE CODE / A DIFFERENT KIND OF CRAFT',now:'CURRENT CHAPTER / STILL IN PROGRESS',social:'OPEN CHANNELS / SAY SOMETHING'};
const titles:Record<Chapter,string>={about:'A little context.',work:'Under the hood.',lab:'What happens if…',notes:'Leave room for a thought.',shelf:'One question leads to another.',studio:'A different kind of signal.',now:'What’s next?',social:'Let’s connect the dots.'};

export default function Notebook(){
  const [chapter,setChapter]=useState<Chapter|null>(null),[article,setArticle]=useState<Entry|null>(null);
  const [records,setRecords]=useState<Entry[]>(initialEntries),[visited,setVisited]=useState<Chapter[]>([]),[hover,setHover]=useState<string|null>(null);
  const [positions,setPositions]=useState<Record<string,{x:number;y:number}>>({}),[indexOpen,setIndexOpen]=useState(false),[layer,setLayer]=useState(0),[time,setTime]=useState(''),[sound,setSound]=useState(false),[updatesUnavailable,setUpdatesUnavailable]=useState(false);
  const map=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),soundRef=useRef<AudioContext|null>(null),lastFocus=useRef<HTMLElement|null>(null);
  const drag=useRef<{id:string;startX:number;startY:number;x:number;y:number;moved:boolean}|null>(null),skipClick=useRef(false);
  useEffect(()=>{const update=()=>setTime(new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date()));update();const clock=setInterval(update,30000);const abort=new AbortController();fetch('/api/entries',{signal:abort.signal}).then(async r=>{if(r.ok){const d=await r.json() as {entries:Entry[]};if(Array.isArray(d.entries))setRecords(d.entries);else setUpdatesUnavailable(true)}else setUpdatesUnavailable(true)}).catch(()=>setUpdatesUnavailable(true));return()=>{clearInterval(clock);abort.abort();soundRef.current?.close()}},[]);
  useEffect(()=>{const hash=location.hash.slice(1);if(sequence.includes(hash as Chapter))openChapter(hash as Chapter)},[]);
  useEffect(()=>{if(chapter){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[chapter]);
  function playNote(){if(!sound)return;try{const ctx=soundRef.current??new AudioContext();soundRef.current=ctx;void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(380,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(190,ctx.currentTime+.09);gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.13)}catch{setSound(false)}}
  function openChapter(id:Chapter){if(!chapter)lastFocus.current=document.activeElement as HTMLElement;setChapter(id);setArticle(null);setVisited(v=>v.includes(id)?v:[...v,id]);setIndexOpen(false);setLayer(0);playNote()}
  function close(){setChapter(null);setArticle(null)}
  function startDrag(e:PointerEvent<HTMLButtonElement>,id:string,x:number,y:number){if(e.pointerType==='touch')return;drag.current={id,startX:e.clientX,startY:e.clientY,x,y,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}
  function moveDrag(e:PointerEvent<HTMLButtonElement>){const d=drag.current,r=map.current?.getBoundingClientRect();if(!d||!r)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;if(d.moved)setPositions(p=>({...p,[d.id]:{x:Math.max(13,Math.min(87,d.x+dx/r.width*100)),y:Math.max(13,Math.min(85,d.y+dy/r.height*100))}}))}
  function endDrag(){skipClick.current=!!drag.current?.moved;drag.current=null}
  useEffect(()=>{const page=dialog.current?.querySelector('.book-page');if(page)page.scrollTop=0},[chapter,article]);
  const filtered=records.filter(e=>e.kind===chapter);
  return <div className="living-notebook">
    <header className="desk-header"><button className="notebook-wordmark" onClick={()=>{close();setIndexOpen(!indexOpen)}} aria-expanded={indexOpen} aria-controls="notebook-index"><span className="monogram">d/p</span><span>DEVARSH PATEL<small>AN OPEN NOTEBOOK</small></span></button><span className="desk-edition">A SMALL MAP OF A VERY CURIOUS MIND</span><div className="desk-actions"><button onClick={()=>openChapter('about')}>The short version</button><a href="/resume.pdf" target="_blank" rel="noopener noreferrer">Résumé ↗</a><button className="channel" onClick={()=>openChapter('social')}>Let’s talk <span>↗</span></button></div></header>
    <main className="desk" id="main"><div className="desk-caption"><span><i/> OPEN FOR EXPLORATION</span><span>NO RIGHT ORDER. PICK A THREAD.</span></div>
      <div className="thought-map" ref={map}>
        <svg className="connections" viewBox="0 0 1000 720" preserveAspectRatio="none" aria-hidden="true">{chapters.map((c,i)=>{const p=positions[c.id]??c;return <g key={c.id} className={hover===c.id?'lit':''}><path d={`M 470 345 Q ${p.x*10+(i%2?90:-90)} 345 ${p.x*10} ${p.y*7.2}`} className={'connection connection-'+c.id}/><circle r="3" className="traveller"><animateMotion dur={`${8+i*1.7}s`} repeatCount="indefinite" path={`M 470 345 Q ${p.x*10+(i%2?90:-90)} 345 ${p.x*10} ${p.y*7.2}`}/></circle></g>})}<path d="M 200 525 Q 290 650 570 575" className="connection secondary"/><path d="M 740 175 Q 915 210 820 396" className="connection secondary"/></svg>
        <button className="identity-note" onClick={()=>openChapter('about')} onMouseEnter={()=>setHover('about')} onMouseLeave={()=>setHover(null)}><span className="note-meta">HELLO, YOU FOUND ME.</span><strong>Devarsh<br/><em>Patel.</em></strong><span className="identity-underline"/><span className="identity-caption">I build things.<br/>Then I need to know why.</span><span className="identity-open">A FEW WORDS ABOUT ME ↗</span></button>
        <span className="hand-note annotation-one">everything is<br/>connected, somehow.</span><span className="hand-note annotation-two">start anywhere ↗</span>
        {chapters.map(c=>{const p=positions[c.id]??c;return <button key={c.id} className={`map-note note-${c.id} ${visited.includes(c.id)?'visited':''}`} style={{'--x':`${p.x}%`,'--y':`${p.y}%`,'--rotation':`${c.rotation}deg`} as CSSProperties} onMouseEnter={()=>setHover(c.id)} onMouseLeave={()=>setHover(null)} onPointerDown={e=>startDrag(e,c.id,p.x,p.y)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={()=>{drag.current=null}} onClick={()=>{if(skipClick.current){skipClick.current=false;return}openChapter(c.id)}}><span className="note-top"><span>{c.number} / {c.id==='work'?'ENGINEERING':c.id==='lab'?'AI & EXPERIMENTS':c.id==='notes'?'WORDS':c.id==='shelf'?'CURIOSITY':c.id==='studio'?'CREATIVE PRACTICE':'IN PROGRESS'}</span><span className="node-status">{visited.includes(c.id)?'✓':'↗'}</span></span>
          {c.id==='work'&&<div className="mini-system" aria-hidden><span>UI</span><i/><span>API</span><i/><span>DATA</span></div>}
          {c.id==='lab'&&<div className="equation" aria-hidden>what if <span>?</span><small>hypothesis → experiment → learn</small></div>}
          {c.id==='studio'&&<div className="signal-bars" aria-hidden>{Array.from({length:30},(_,i)=><i key={i} style={{height:`${12+Math.abs(Math.sin(i*.8))*28}px`,'--delay':`${i*.08}s`} as CSSProperties}/>)}</div>}
          <strong>{c.label}</strong><span className="note-hint">{c.hint}</span>{c.id==='shelf'&&<span className="shelf-topics">PHILOSOPHY · SPACE · HUMAN BEHAVIOR</span>}
        </button>})}
        <button className="margin-contact" onClick={()=>openChapter('social')}><span>got a good<br/>problem?</span><b>let’s talk ↗</b></button>
        <span className="coordinate coordinate-a">A LOT ON MY MIND / ALWAYS</span><span className="coordinate coordinate-b">P.S. THE NOTES MOVE. TRY DRAGGING ONE.</span>
      </div>
      <div className="desk-bottom"><button className="index-toggle" onClick={()=>setIndexOpen(!indexOpen)} aria-expanded={indexOpen}>☷ <span>Notebook index</span></button><span className="discovery-count"><b>{visited.length.toString().padStart(2,'0')}</b> / 08 THREADS FOLLOWED</span><div className="desk-settings"><button onClick={()=>{setSound(!sound);if(sound)soundRef.current?.suspend()}} aria-pressed={sound}>SOUND {sound?'ON':'OFF'}</button><button onClick={()=>setPositions({})}>RESET DESK</button><span>{time||'—:—'} IST</span></div></div>
      {indexOpen&&<nav className="notebook-index" id="notebook-index" aria-label="Notebook chapters"><span className="note-meta">THE TABLE OF CONTENTS</span>{sequence.map((id,i)=><button key={id} onClick={()=>openChapter(id)}><small>{String(i+1).padStart(2,'0')}</small><span>{id==='about'?'The person':id==='social'?'All socials':id==='work'?'Engineering work':kinds[id].title}</span><span>↗</span></button>)}<a href="/admin">Open my editor ↗</a></nav>}
    </main>
    <dialog ref={dialog} className={`reading-room room-${chapter??'about'}`} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}} aria-labelledby="chapter-title">
      {chapter&&<div className="reading-layout"><aside className="book-spine"><span className="spine-mark">d/p</span><nav>{sequence.map((id,i)=><button className={id===chapter?'active':''} key={id} title={id==='about'?'About':id==='social'?'Connect':kinds[id].title} onClick={()=>openChapter(id)} aria-label={id==='about'?'About':id==='social'?'Connect':kinds[id].title}>{String(i+1).padStart(2,'0')}</button>)}</nav><span className="spine-label">AN OPEN NOTEBOOK</span></aside><div className="book-page"><div className="page-toolbar"><span>{captions[chapter]}</span><button onClick={close} autoFocus aria-label="Close notebook chapter">BACK TO THE MAP <b>×</b></button></div><div className="page-content" key={chapter+(article?.id??'')}>{updatesUnavailable&&<p className="chapter-note" role="status">Saved updates could not load. Showing the introductory notebook.</p>}<span className="page-number">{String(sequence.indexOf(chapter)+1).padStart(2,'0')} / 08</span><h1 id="chapter-title">{article?article.title:titles[chapter]}</h1>
        {article?<><button className="back-to-chapter" onClick={()=>setArticle(null)}>← Back to {kinds[article.kind].title}</button><p className="chapter-lede">{article.summary}</p><div className="notebook-prose">{article.body.split(/\n\n+/).map((p,i)=>{const [first,...rest]=p.split('\n');return <section key={i}>{rest.length>0?<><h3>{first}</h3><p>{rest.join('\n')}</p></>:<p>{p}</p>}</section>})}</div>{article.url&&<a className="ink-link" href={article.url} target="_blank" rel="noopener noreferrer">Open the reference ↗</a>}{article.attachment&&<p><a className="ink-link" href={article.attachment} target="_blank" rel="noopener noreferrer">Open attachment ↗</a></p>}<div className="follow-thread"><span>THERE’S A CONNECTION HERE…</span><button onClick={()=>openChapter(article.kind==='work'?'lab':'work')}>{article.kind==='work'?'From systems to experiments':'Back to the systems'} ↗</button></div></>:
        <>
          {chapter==='about'&&<><p className="chapter-lede">Developer. Storyteller.<br/><em>Compulsively curious human.</em></p><div className="notebook-prose"><p>I build things. And then I obsessively try to understand why they work.</p><p>My work moves between React interfaces, Python and Node.js APIs, AWS infrastructure, and the data underneath. I’ve owned a streaming platform’s stack, built data pipelines, worked on predictive churn models, and translated the findings for leadership.</p><p>Then there’s the other side: writing, video editing, sound design. Reading about Stoic philosophy, astronomy, psychology, and longevity. Following a question further than I intended.</p><blockquote>“I don’t just write code. I ask why the feature matters, who it’s for, and what the data is actually trying to tell us.”</blockquote></div><div className="personal-footnotes"><div><small>EDUCATION</small><p>M.S. Computer Science<br/>Loyola Marymount University, 2025</p><p>B.Tech Information Technology<br/>Indus University, 2022</p></div><div><small>THE NEXT CHAPTER</small><p>Remote AI development & engineering.<br/>Creative work worth making.</p><a className="ink-link" href="/resume.pdf" target="_blank" rel="noopener noreferrer">The résumé version ↗</a></div></div></>}
          {chapter==='work'&&<><p className="chapter-lede">A product is a stack of decisions.<br/><em>Pick a layer.</em></p><div className="system-explorer"><div className="system-tabs" role="tablist" aria-label="System layers">{['Interface','Engine','Infrastructure','Insight'].map((label,i)=><button role="tab" aria-selected={layer===i} key={label} onClick={()=>{setLayer(i);playNote()}}><span>0{i+1}</span>{label}</button>)}</div><div className="system-detail" role="tabpanel"><span className="note-meta">GEOFLIXZ+ / INSIDE THE SYSTEM</span><h2>{['The part people touch.','The logic between the pixels.','The foundation underneath.','The reason for the data.'][layer]}</h2><p>{['React interfaces for a streaming platform. Full-stack ownership meant connecting the experience on screen to the services behind it.','Node.js and Python APIs connected the application to the systems and data it depended on.','AWS infrastructure with S3, EC2, and Lambda. Data warehousing and automated ETL with Redshift, Glue, and Athena.','Python cohort analyses, predictive churn modeling, and Tableau and Power BI presentations for the CEO.'][layer]}</p></div></div></>}
          {chapter==='lab'&&<><p className="chapter-lede">The interesting part lives between<br/><em>“I think” and “I tested.”</em></p><div className="lab-process"><span>QUESTION</span><i>→</i><span>BUILD</span><i>→</i><span>OBSERVE</span><i>↺</i></div><p className="chapter-note">My current foundation is production software, data engineering, and applied predictive modeling. This is where I’m building a more rigorous experiment log.</p></>}
          {chapter==='notes'&&<><p className="chapter-lede">Some thoughts need more space<br/><em>than the margin allows.</em></p>{filtered.length===0&&<div className="blank-page"><span className="hand-note">The first page is still unwritten.</span><p>Essays, observations, and the questions I keep coming back to will live here.</p><div className="ruled-lines" aria-hidden/></div>}</>}
          {chapter==='shelf'&&<><p className="chapter-lede">Not a list of books I’ve finished.<br/><em>A map of things I’m drawn to.</em></p><div className="interest-index">{[['01','Stoic philosophy','How do we choose what deserves our attention?'],['02','Astronomy','What changes when you zoom all the way out?'],['03','Psychology & human behavior','Why do people do what they do?'],['04','Longevity research','What does it mean to live well, for longer?']].map(([n,title,q])=><details key={n}><summary><small>{n}</small><span>{title}</span><b>+</b></summary><p>{q}</p></details>)}</div><p className="chapter-note">Personal interests, drawn from my own reading and curiosity. Specific books and notes will appear as I add them.</p></>}
          {chapter==='studio'&&<><p className="chapter-lede">Sometimes the right tool<br/><em>isn’t a code editor.</em></p><div className="studio-tracks"><div><span>01 / WORDS</span><h2>Make an idea land.</h2><p>Content creation, content writing, and technical storytelling.</p></div><div><span>02 / FRAMES</span><h2>Find the rhythm.</h2><p>Video editing in DaVinci Resolve. Shaping footage into a story.</p></div><div><span>03 / FREQUENCIES</span><h2>Make it felt.</h2><p>Sound design. The layer you notice when it’s missing.</p></div></div><a className="ink-link" href="mailto:pateldevarsh43@gmail.com?subject=Creative%20project">Have something in mind? ↗</a>{filtered.length===0&&<p className="chapter-note">Creative samples are not published yet. Get in touch to discuss a project.</p>}</>}
          {chapter==='now'&&<p className="chapter-lede">A work in progress.<br/><em>Which is exactly the point.</em></p>}
          {chapter==='social'&&<><p className="chapter-lede">A role. A project. A strange idea.<br/><em>I’m listening.</em></p><a className="contact-note" href="mailto:pateldevarsh43@gmail.com"><small>THE DIRECT LINE</small><strong>pateldevarsh43<br/>@gmail.com</strong><span>WRITE TO ME ↗</span></a>{records.filter(e=>e.kind==='social'&&e.url).map(e=><a className="social-line" href={e.url} target="_blank" rel="noopener noreferrer" key={e.id}><span>{e.title}</span><small>{e.summary}</small><b>↗</b></a>)}<p className="chapter-note">Open to remote AI development and engineering opportunities, content writing, video editing, and creative collaborations.</p></>}
          {chapter!=='social'&&filtered.length>0&&<div className="chapter-entries"><span className="note-meta">{chapter==='work'?'THE BUILD NOTES':chapter==='lab'?'FROM THE LOG':'IN THIS CHAPTER'}</span>{filtered.map((entry,i)=><button key={entry.id} onClick={()=>{setArticle(entry);playNote()}}><small>{String(i+1).padStart(2,'0')}</small><div><h2>{entry.title}</h2><p>{entry.summary}</p></div><b>↗</b></button>)}</div>}
          <div className="follow-thread"><span>FOLLOW ANOTHER THREAD</span><button onClick={()=>openChapter(sequence[(sequence.indexOf(chapter)+1)%sequence.length])}>{titles[sequence[(sequence.indexOf(chapter)+1)%sequence.length]]} ↗</button></div>
        </>}
      </div><div className="page-footer"><span>DEVARSH PATEL / AN OPEN NOTEBOOK</span><span>NOTHING HERE IS THE WHOLE STORY.</span></div></div></div>}
    </dialog>
  </div>;
}

export function Footer(){return <footer className="notebook-footer"><a href="/">← Back to the map</a><span>DEVARSH PATEL / AN OPEN NOTEBOOK</span><a href="/admin">Notebook editor ↗</a></footer>}
