import * as THREE from 'three';

/** Creates the flight scene and exposes navigation without driving React on every frame. */
export function createUniverse(canvas:HTMLCanvasElement,labels:HTMLDivElement,onArrival:()=>void){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'low-power'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor('#050a12');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,1,.1,900);scene.add(camera);
 const anchors=[new THREE.Vector3(-8,-4,0),new THREE.Vector3(14,1,-15),new THREE.Vector3(24,15,-55)];
 const homeCamera=new THREE.Vector3(0,10,43),homeLook=new THREE.Vector3(0,3,-10);camera.position.copy(homeCamera);camera.lookAt(homeLook);
 const look=homeLook.clone(),targetLook=homeLook.clone(),targetCamera=homeCamera.clone();let flying=false,paused=false,disposed=false,time=0,frame=0;
 const ambient=new THREE.AmbientLight('#6b91ad',1.5);scene.add(ambient);const sunlight=new THREE.DirectionalLight('#ffdec2',4);sunlight.position.set(-30,20,25);scene.add(sunlight);
 let seed=531;function random(){seed=(seed*16807)%2147483647;return (seed-1)/2147483646}
 const stars=new Float32Array(2400*3),colors=new Float32Array(stars.length);for(let i=0;i<stars.length;i+=3){stars[i]=(random()-.5)*500;stars[i+1]=(random()-.5)*300;stars[i+2]=-random()*360-40;const c=new THREE.Color().setHSL(.08+random()*.55,.15+random()*.2,.5+random()*.4);colors[i]=c.r;colors[i+1]=c.g;colors[i+2]=c.b}
 const starGeometry=new THREE.BufferGeometry();starGeometry.setAttribute('position',new THREE.BufferAttribute(stars,3));starGeometry.setAttribute('color',new THREE.BufferAttribute(colors,3));scene.add(new THREE.Points(starGeometry,new THREE.PointsMaterial({size:.17,vertexColors:true,transparent:true,opacity:.8,sizeAttenuation:true})));
 const planet=new THREE.Mesh(new THREE.SphereGeometry(6,72,48),new THREE.ShaderMaterial({uniforms:{},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 vN;varying vec3 vP;float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}void main(){vec3 p=vP;float n=noise(p*1.4)*.55+noise(p*4.)*.25+noise(p*12.)*.13+noise(p*32.)*.07;vec3 rock=mix(vec3(.10,.16,.18),vec3(.61,.43,.29),smoothstep(.26,.72,n));float light=max(dot(normalize(vN),normalize(vec3(-.8,.5,1.))),0.);float rim=pow(1.-max(vN.z,0.),3.);vec3 c=rock*(.035+light*1.3)+vec3(.22,.48,.61)*rim*.33;gl_FragColor=vec4(c,1.);}` }));planet.position.copy(anchors[1]);planet.rotation.z=.2;scene.add(planet);
 const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(6.13,48,32),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,vertexShader:`varying vec3 n;void main(){n=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 n;void main(){float glow=pow(1.-abs(n.z),5.);gl_FragColor=vec4(.29,.64,.85,glow*.45);}`}));atmosphere.position.copy(planet.position);scene.add(atmosphere);
 const metal=new THREE.MeshStandardMaterial({color:'#7d8a8b',roughness:.48,metalness:.8}),dark=new THREE.MeshStandardMaterial({color:'#26343c',roughness:.6,metalness:.7}),light=new THREE.MeshBasicMaterial({color:'#9cded8'});
 function mesh(geometry:THREE.BufferGeometry,material:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);parent.add(m);return m}
 const station=new THREE.Group();station.position.copy(anchors[0]);station.rotation.set(.9,.25,.3);scene.add(station);
 mesh(new THREE.TorusGeometry(3.2,.15,12,80),metal,station);mesh(new THREE.TorusGeometry(3.3,.025,6,80),light,station);mesh(new THREE.CylinderGeometry(.6,.8,2,12),metal,station).rotation.x=Math.PI/2;
 for(let i=0;i<4;i++){const arm=new THREE.Group();arm.rotation.z=i*Math.PI/2;station.add(arm);mesh(new THREE.BoxGeometry(2.8,.12,.18),metal,arm,1.8);mesh(new THREE.BoxGeometry(1.2,.65,.5),dark,arm,3.1);mesh(new THREE.BoxGeometry(.85,.08,.53),light,arm,3.1)}
 const blackHole=new THREE.Group();blackHole.position.copy(anchors[2]);blackHole.rotation.z=.2;scene.add(blackHole);
 mesh(new THREE.SphereGeometry(3,48,32),new THREE.MeshBasicMaterial({color:'#020305'}),blackHole);
 const disk=mesh(new THREE.RingGeometry(3.2,8,120),new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:false,vertexShader:`varying vec2 p;void main(){p=position.xy;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 p;void main(){float r=length(p);float a=atan(p.y,p.x);float bands=.55+.45*sin(r*25.+sin(a*4.)*1.5);float fall=pow(max(0.,1.-(r-3.2)/4.8),1.8);vec3 color=mix(vec3(.7,.25,.06),vec3(1.,.87,.62),fall);gl_FragColor=vec4(color*(1.+fall),fall*(.5+.5*bands));}`} ),blackHole);disk.rotation.x=1.24;
 const halo=mesh(new THREE.TorusGeometry(3.08,.08,12,100),new THREE.MeshBasicMaterial({color:'#ffe5af'}),blackHole);halo.scale.y=.96;
 const arc=mesh(new THREE.TorusGeometry(3.55,.09,10,100,Math.PI),new THREE.MeshBasicMaterial({color:'#d9a269',transparent:true,opacity:.5}),blackHole);arc.position.z=-.15;
 const asteroids=new THREE.Group();scene.add(asteroids);const asteroidGeo=new THREE.IcosahedronGeometry(.35,0);for(let i=0;i<65;i++){const a=random()*Math.PI*2,r=10+random()*4;const rock=mesh(asteroidGeo,dark,asteroids,14+Math.cos(a)*r,-1+random()*2,-15+Math.sin(a)*r);rock.rotation.set(random()*3,random()*3,random()*3);rock.scale.setScalar(.25+random()*1.1)}
 // Keep the ship in the foreground, like a third-person flight camera.
 const ship=new THREE.Group();camera.add(ship);ship.position.set(1.7,-2.8,-11);ship.scale.setScalar(.65);ship.rotation.set(.12,Math.PI,.08);
 const hull=mesh(new THREE.ConeGeometry(.48,2.5,5),metal,ship);hull.rotation.x=Math.PI/2;
 mesh(new THREE.BoxGeometry(2.4,.09,.65),dark,ship,0,-.08,.45);mesh(new THREE.BoxGeometry(.28,.3,.6),new THREE.MeshStandardMaterial({color:'#caa46a',metalness:.6,roughness:.4}),ship,-1,-.04,.35);mesh(new THREE.BoxGeometry(.28,.3,.6),metal,ship,1,-.04,.35);
 const cockpit=mesh(new THREE.SphereGeometry(.26,12,8),new THREE.MeshStandardMaterial({color:'#77b8c9',emissive:'#347a9c',emissiveIntensity:.7,metalness:.8,roughness:.2}),ship,0,.22,-.2);cockpit.scale.set(1,.6,1.9);
 const exhaustMaterial=new THREE.MeshBasicMaterial({color:'#9adff1',transparent:true,opacity:.7});const exhaust=mesh(new THREE.ConeGeometry(.18,1.7,16),exhaustMaterial,ship,0,0,1.6);exhaust.rotation.x=-Math.PI/2;
 const labelNodes=Array.from(labels.querySelectorAll<HTMLButtonElement>('[data-place]'));const projection=new THREE.Vector3();let width=1,height=1;
 function resize(){width=canvas.clientWidth;height=canvas.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.fov=width<650?78:48;camera.updateProjectionMatrix()}
 const observer=new ResizeObserver(resize);observer.observe(canvas);resize();const clock=new THREE.Clock();
 function draw(){if(disposed)return;frame=requestAnimationFrame(draw);const dt=Math.min(clock.getDelta(),.04);if(document.hidden)return;if(!paused)time+=dt;
  if(flying){const k=paused?1:1-Math.exp(-dt*1.7);camera.position.lerp(targetCamera,k);look.lerp(targetLook,k);if(camera.position.distanceTo(targetCamera)<.05){flying=false;onArrival()}}
  camera.lookAt(look);if(!paused){planet.rotation.y+=dt*.025;station.rotation.z+=dt*.04;asteroids.rotation.y=Math.sin(time*.015)*.018;ship.position.y=-2.8+Math.sin(time*.8)*.08;ship.rotation.z= .08+Math.sin(time*.6)*.025+(flying?.16:0);exhaust.scale.y=(flying?2:1)+Math.sin(time*12)*.08;}
  for(let i=0;i<labelNodes.length;i++){projection.copy(anchors[i]);projection.y-=i===1?7:i===2?5:4;projection.project(camera);const x=(projection.x*.5+.5)*width,y=(-projection.y*.5+.5)*height;const node=labelNodes[i];const visible=projection.z<1&&x>65&&x<width-75&&y>100&&y<height-205;node.style.visibility=visible?'visible':'hidden';node.style.transform=`translate(${x}px,${y}px) translate(-50%,0)`}
  renderer.render(scene,camera);
 }
 draw();const lost=(event:Event)=>{event.preventDefault();cancelAnimationFrame(frame)};canvas.addEventListener('webglcontextlost',lost);
 return {go(id:number){if(id===0){targetCamera.copy(homeCamera);targetLook.copy(homeLook)}else{targetLook.copy(anchors[id]);targetCamera.copy(anchors[id]).add(new THREE.Vector3(id===1?3:0,4,id===1?27:30))}flying=true},pause(value:boolean){paused=value},dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();canvas.removeEventListener('webglcontextlost',lost);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.Points){geometries.add(object.geometry);const mats=Array.isArray(object.material)?object.material:[object.material];mats.forEach(m=>materials.add(m))}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose()}};
}


