'use client';
import {useEffect,useRef,useState} from 'react';
import './universe.css';
const places=[{id:0,name:'Home Station',type:'01 / ABOUT ME'},{id:1,name:'The Foundry',type:'02 / ENGINEERING & AI'},{id:2,name:'The Unknown',type:'03 / THE EVENT HORIZON'}];
export default function Universe(){
 const canvas=useRef<HTMLCanvasElement>(null),labels=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);
 const flight=useRef<{go:(id:number)=>void;dispose:()=>void;pause:(v:boolean)=>void}|null>(null);
 const [destination,setDestination]=useState(0),[arrived,setArrived]=useState(true),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[still,setStill]=useState(false),[panel,setPanel]=useState<'dock'|'map'>('dock');
 useEffect(()=>{let disposed=false;import('./universe-scene').then(({createUniverse})=>{if(disposed||!canvas.current||!labels.current)return;try{flight.current=createUniverse(canvas.current,labels.current,()=>setArrived(true));setReady(true);if(matchMedia('(prefers-reduced-motion: reduce)').matches){flight.current.pause(true);setStill(true)}}catch{setFailed(true)}}).catch(()=>setFailed(true));return()=>{disposed=true;flight.current?.dispose()}},[]);
 function travel(id:number){setDestination(id);setArrived(false);flight.current?.go(id);dialog.current?.close()}
 function open(which:'dock'|'map'){setPanel(which);flight.current?.pause(true);dialog.current?.showModal()}
 return <div className={`cosmos ${destination!==0?"scene-away":""}`}><a className="space-skip" href="/quick">Skip flight — open readable portfolio</a><canvas ref={canvas} aria-label="A three-dimensional solar system with an orbital station, a rocky planet, and a distant black hole"/>
 <header className="space-header"><a href="/" className="space-brand"><span aria-hidden="true">✳</span><div>DEVARSH PATEL<small>A PERSONAL UNIVERSE</small></div></a><nav aria-label="Portfolio"><a href="/quick">Quick portfolio ↗</a><a href="/resume.pdf" target="_blank" rel="noreferrer">Résumé ↗</a><a className="space-contact" href="mailto:pateldevarsh43@gmail.com">Contact <span>↗</span></a></nav></header>
 <main className="space-intro"><p className="space-eyebrow"><i/> PERSONAL EXPEDITION / VOL. 01</p><h1>A curious mind.<br/>An open <em>universe.</em></h1><p>Software engineer. AI explorer. Creator.<br/>A few things about me, somewhere among the stars.</p><button onClick={()=>open('map')} className="space-outline">Choose a destination <span>↗</span></button></main>
 <div className="space-coordinate" aria-hidden="true">SOL SYSTEM — DP / 001<br/>EXPLORATION IS THE POINT.</div>
 <div ref={labels} className="space-labels">{places.map(p=><button key={p.id} data-place={p.id} onClick={()=>travel(p.id)} aria-pressed={destination===p.id} disabled={!ready}><span className="place-cross">+</span><span><small>{p.type}</small>{p.name}<b>SET COURSE ↗</b></span></button>)}</div>
 <div className="space-bottom"><div className="space-location"><span className="space-eyebrow">{arrived?'IN ORBIT':'AUTOPILOT ENGAGED'}</span><strong aria-live="polite">{places[destination].name}</strong><span>{arrived?'Take your time. There’s no right order.':'A new perspective, just ahead.'}</span></div><button className="space-dock" disabled={!ready||!arrived} onClick={()=>open('dock')}>{arrived?'Dock & explore':'In transit…'} <span>↗</span></button><div className="space-controls"><button onClick={()=>open('map')}>⊞ <span>System map</span></button><button aria-pressed={still} onClick={()=>{setStill(!still);flight.current?.pause(!still)}}>{still?'▶ Motion off':'Ⅱ Pause motion'}</button></div></div>
 {!ready&&<p className="space-status" role="status">{failed?< >This device couldn’t open the 3D scene. <a href="/quick">Explore the readable portfolio ↗</a></>:'Preparing your little corner of the universe…'}</p>}
 <dialog ref={dialog} className="space-dialog" onClose={()=>flight.current?.pause(still)} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}><button className="space-close" onClick={()=>dialog.current?.close()} aria-label="Close panel">×</button>
 {panel==='map'?<><p className="space-eyebrow">FLIGHT COMPUTER / DESTINATIONS</p><h2>Where to?</h2><p>Three places to explore in this first expedition.</p><div className="space-map">{places.map(p=><button key={p.id} onClick={()=>travel(p.id)}><small>{p.type}</small><strong>{p.name}</strong><span>Set course ↗</span></button>)}</div><p className="space-coming">Next chapters: creative work · writing · interests · flight record · communications</p><a href="/quick">Prefer a simple page? Quick portfolio ↗</a></>:destination===0?<><p className="space-eyebrow">HOME STATION / ABOUT ME</p><h2>Hi, I’m Devarsh.</h2><p>I build software. Then I need to understand why it works.</p><p>My work spans full-stack development, cloud infrastructure, data, and predictive modeling. Beyond code: writing, video editing, sound design, and a persistent fascination with the universe.</p><div className="space-facts"><span>M.S. Computer Science<br/><b>Loyola Marymount University</b></span><span>Looking ahead<br/><b>Remote AI & software roles</b></span></div><button className="space-dock" onClick={()=>travel(1)}>Explore my engineering work ↗</button></>:destination===1?<><p className="space-eyebrow">THE FOUNDRY / ENGINEERING & AI</p><h2>Behind the<br/><em>play button.</em></h2><p>At GEOFLIXZ+, I owned the technical stack across React interfaces, Node.js and Python APIs, and AWS infrastructure.</p><p>I also worked on data pipelines and predictive churn modeling—connecting product behavior with decisions.</p><div className="space-facts"><span>STACK<br/><b>React · Node.js · Python · AWS</b></span></div><a className="space-dock" href="/entry/streaming-platform">Read the project story ↗</a></>:<><p className="space-eyebrow">THE UNKNOWN / A SMALL DETOUR</p><h2>Some questions<br/><em>pull you in.</em></h2><p>Astronomy is one of the places my curiosity keeps returning to. Scale, time, gravity—the familiar rules become strange when you look far enough.</p><p>This black hole is an artistic interpretation: a dark center surrounded by an accretion disk. A small reminder that there’s always more to understand.</p><button className="space-dock" onClick={()=>travel(0)}>Return to Home Station ↗</button></>}
 </dialog></div>
}

